# Generated by Django 2.2.6 on 2019-10-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191018_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_answered',
        ),
    ]
