# Generated by Django 2.2.6 on 2019-10-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191018_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location'),
        ),
        migrations.AlterField(
            model_name='question',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location'),
        ),
    ]
