# Generated by Django 2.2.6 on 2019-10-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=20)),
                ('location_id', models.PositiveIntegerField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
