# Generated by Django 2.2.5 on 2019-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191030_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_type',
            field=models.TextField(default='LINE', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.TextField(default='LINE', max_length=100),
        ),
    ]
