# Generated by Django 2.2.5 on 2019-10-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_subscription'),
        ('users', '0014_auto_20191030_1641'),
    ]

    operations = [
    ]
