# Generated by Django 2.2.6 on 2019-11-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20191031_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='location_id',
            new_name='location',
        ),
    ]
