# Generated by Django 2.2.6 on 2019-11-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191101_2348'),
        ('users', '0015_merge_20191031_1509'),
    ]

    operations = [
    ]
