# Generated by Django 2.2.6 on 2019-11-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191102_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default='LONG LINE', max_length=100),
        ),
    ]
