# Generated by Django 2.2.6 on 2019-11-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_follows'),
        ('users', '0011_auto_20191105_0259'),
    ]

    operations = [
    ]
