# Generated by Django 2.2.6 on 2019-11-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191116_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rated', models.BooleanField(default=False)),
                ('is_up', models.BooleanField(default=True)),
                ('connected_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Answer')),
            ],
        ),
    ]
