# Generated by Django 2.2.6 on 2019-12-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate_down',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate_up',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
