# Generated by Django 2.2.6 on 2019-12-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20191201_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['publish_date_time']},
        ),
    ]
