# Generated by Django 2.2.6 on 2019-12-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20191207_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-publish_date_time']},
        ),
    ]
