# Generated by Django 2.2.6 on 2019-12-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20191207_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='publish_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='publish_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
