# Generated by Django 2.2.5 on 2019-12-08 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20191208_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='users_rated_answers',
            field=models.ManyToManyField(related_name='rated_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
