# Generated by Django 2.2.5 on 2019-12-08 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0030_auto_20191208_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='users_rated_answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='users_rated_down_answers',
            field=models.ManyToManyField(related_name='rated_down_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='users_rated_up_answers',
            field=models.ManyToManyField(related_name='rated_up_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
