# Generated by Django 2.2.5 on 2019-12-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20191208_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_rated',
        ),
    ]
