# Generated by Django 2.2.8 on 2019-12-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_answer_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rated_down_answers',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rated_down_answers', to='users.Answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rated_up_answers',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rated_up_answers', to='users.Answer'),
        ),
    ]
