# Generated by Django 2.2.8 on 2019-12-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20191211_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rated_down_answers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rated_up_answers',
        ),
    ]
