# Generated by Django 2.2.8 on 2019-12-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20191211_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='follow_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
