# Generated by Django 2.2.6 on 2019-12-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_question_follow_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['rank_score']},
        ),
        migrations.AddField(
            model_name='profile',
            name='rank_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reliability',
            field=models.FloatField(default=0),
        ),
    ]
