# Generated by Django 2.2.6 on 2019-12-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_profile_reliability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['ranking_score']},
        ),
        migrations.AddField(
            model_name='profile',
            name='ranking_score',
            field=models.FloatField(default=0),
        ),
    ]
