# Generated by Django 2.2.8 on 2019-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20191216_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
